name: build-and-test

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: update submodule
              run: git submodule update --init --depth=1

            - name: Install apt packages
              run: |
                  sudo apt-get install libeigen3-dev libgtest-dev

            - name: Build c++ via cmake
              run: |
                  mkdir build
                  cd build
                  cmake ..
                  make

            - name: Test c++
              run: |
                  cd build
                  ctest --verbose
